[Layout1]
cardtemplate = card1.png
piccount = 1

layout_in_foreground = True

resize_image_x_1 = 1250
resize_image_y_1 = 900
rotate_image_1 = 0
position_image_x_1 = 580
position_image_y_1 = 333


[Layout2]
cardtemplate = card2.png
piccount = 1

layout_in_foreground = True

resize_image_x_1 = 1459
resize_image_y_1 = 860
rotate_image_1 = 0
position_image_x_1 = 58
position_image_y_1 = 370

; resize_image_x_2 = 604
; resize_image_y_2 = 445
; rotate_image_2 = 0
; position_image_x_2 = 316
; position_image_y_2 = 625
